# This file was generated by GoReleaser. DO NOT EDIT.
cask "pace" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "c614e08cbf517a9f50c60247f46f1a7f3a96741c0fb6f91effd2297d048c1965"
      url "https://github.com/soundadam/pace/releases/download/v#{version}/pace_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "26d4b3087989cbed28c409dc4678e1d37a4bd455fd940d664641122787121c96"
      url "https://github.com/soundadam/pace/releases/download/v#{version}/pace_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f48d8ddc80019ee7c77fa9765d30bc53fddfd1d34077559b615fb69b6b5e7116"
      url "https://github.com/soundadam/pace/releases/download/v#{version}/pace_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "116dcdfb5c54c770257affccd6bba4a472b335f0763d2e599ceaea218fc33dd4"
      url "https://github.com/soundadam/pace/releases/download/v#{version}/pace_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pace"
  desc "Speed tests for proxies, campus intranets and CERNET"
  homepage "https://github.com/soundadam/pace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pace"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/pace"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    pace is MIT licensed.

    The optional measurement helpers are separate programs with their own
    licenses and are NOT bundled with this package:
      - librespeed-cli (LGPL-3.0-only)
      - ndt7-client (Apache-2.0)
    pace never downloads them automatically. Run `pace doctor`
    to see which helpers are available on this machine.
  EOS
end
