# This file was generated by GoReleaser. DO NOT EDIT.
cask "soundprobe" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "68522a061b5d21e934309dfc7d02d7030d658716df0d2d5f57e9f687108369ed"
      url "https://github.com/soundadam/soundprobe/releases/download/v#{version}/soundprobe_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "87204a336a0abb8af6f3bd15d305a8d2829f1ce4481c91e70a468e7260a19450"
      url "https://github.com/soundadam/soundprobe/releases/download/v#{version}/soundprobe_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3b58df3fc06cca4b1093a1b2ee31192a8e4d4e8eebc4742c727c4e84e9d20426"
      url "https://github.com/soundadam/soundprobe/releases/download/v#{version}/soundprobe_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cea3974fdb60feda49611ab4d22ed68e7bf91fc5793d700612d9cde6929b1b27"
      url "https://github.com/soundadam/soundprobe/releases/download/v#{version}/soundprobe_#{version}_linux_amd64.tar.gz"
    end
  end

  name "soundprobe"
  desc "Education-network-first network path measurements"
  homepage "https://github.com/soundadam/soundprobe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "soundprobe"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/soundprobe"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    soundprobe is MIT licensed.

    The optional measurement helpers are separate programs with their own
    licenses and are NOT bundled with this package:
      - librespeed-cli (LGPL-3.0-only)
      - ndt7-client (Apache-2.0)
    soundprobe never downloads them automatically. Run `soundprobe doctor`
    to see which helpers are available on this machine.
  EOS
end
